language: node_js
node_js:
  - "8"

cache:
  directories:
    - "node_modules"

install:
  - npm install
  - npm run build

script:
  - echo "Skipping tests"
 
after_success:
  - npm run lint
  - npm run write-good

notifications:
  email: false
