module.exports = {
  '/android/': [
    ['/', '⬆️ Home'],
    {
      title: 'Android',
      icon: 'fab fa-android',
      collapsable: false,
      children: [
        '/android/',
        '/android/fire-os',
      ],
    },
    ['/comp-sci/', '➡️ Computer Science'],
  ],
  '/comp-sci/': [
    ['/', '⬆️ Home'],
    ['/android/', '⬅️ Android'],
    {
      title: 'Computer Science',
      icon: 'fas fa-robot',
      collapsable: false,
      children: [
        '/comp-sci/',
        '/comp-sci/ai',
        '/comp-sci/ml',
      ],
    },
    ['/databases/', '➡️ Databases'],
  ],
  '/databases/': [
    ['/', '⬆️ Home'],
    ['/comp-sci/', '⬅️ Computer Science'],
    {
      title: 'Databases',
      icon: 'fas fa-database',
      collapsable: false,
      children: [
        '/databases/',
        '/databases/mysql',
        '/databases/postgres',
      ],
    },
    ['/devops/', '➡️ DevOps'],
  ],
  '/devops/': [
    ['/', '⬆️ Home'],
    ['/databases/', '⬅️ Databases'],
    {
      title: 'DevOps',
      icon: 'far fa-user-hard-hat',
      collapsable: false,
      children: [
        '/devops/',
        '/devops/ansible',
      ],
    },
    ['/graphic-design/', '➡️ Graphic Design'],
  ],
  '/graphic-design/': [
    ['/', '⬆️ Home'],
    ['/devops/', '⬅️ DevOps'],
    {
      title: 'Graphic Design',
      icon: 'fas fa-pencil-ruler',
      collapsable: false,
      children: [
        '/graphic-design/',
        '/graphic-design/adobe-illustrator',
        '/graphic-design/design-systems',
        '/graphic-design/pen-plotters',
        '/graphic-design/svg',
      ],
    },
    ['/lists/', '➡️ Lists'],
  ],
  '/lists/': [
    ['/', '⬆️ Home'],
    ['/graphic-design/', '⬅️ Graphic Design'],
    {
      title: 'Lists',
      icon: 'fas fa-stream',
      collapsable: false,
      children: [
        '/lists/',
        '/lists/books',
        '/lists/films',
        '/lists/tv-shows',
        '/lists/video-games',
      ],
    },
    ['/pentesting/', '➡️ Pentesting'],
  ],
  '/pentesting/': [
    ['/', '⬆️ Home'],
    ['/lists/', '⬅️ Lists'],
    {
      title: 'Pentesting',
      icon: 'fas fa-pen',
      collapsable: false,
      children: [
        '/pentesting/',
        '/pentesting/metasploit',
        '/pentesting/nmap',
      ],
    },
    ['/programming/', '➡️ Programming'],
  ],
  '/programming/': [
    ['/', '⬆️ Home'],
    ['/pentesting/', '⬅️ Pentesting'],
    {
      title: 'Programming',
      icon: 'fas fa-laptop-code',
      collapsable: false,
      children: [
        '/programming/',
        '/programming/data-science/',
        '/programming/js/',
        '/programming/php/',
        '/programming/python/',
        '/programming/static-website-generators/',
        '/programming/css',
        '/programming/github',
        '/programming/go',
        '/programming/methodology',
        '/programming/r',
      ],
    },
    {
      title: 'Data Science',
      icon: 'fas fa-table',
      collapsable: false,
      children: [
        '/programming/data-science/',
        '/programming/data-science/organizing-projects',
      ],
    },
    {
      title: 'JavaScript',
      icon: 'fab fa-js-square',
      collapsable: false,
      children: [
        '/programming/js/',
        '/programming/js/vuejs',
      ],
    },
    {
      title: 'PHP',
      icon: 'fab fa-php',
      collapsable: false,
      children: [
        '/programming/php/',
        '/programming/php/laravel',
        '/programming/php/wordpress',
      ],
    },
    {
      title: 'Python',
      icon: 'fab fa-python',
      collapsable: false,
      children: [
        '/programming/python/',
        '/programming/python/anaconda',
        '/programming/python/celery',
        '/programming/python/django',
        '/programming/python/jupyter',
        '/programming/python/pandas',
        '/programming/python/regexes',
        '/programming/python/web-scraping',
      ],
    },
    {
      title: 'Static Website Generators',
      icon: 'fas fa-browser',
      collapsable: false,
      children: [
        '/programming/static-website-generators/',
        '/programming/static-website-generators/vuepress',
      ],
    },
    ['/setup/', '➡️ Setup'],
  ],
  '/setup/': [
    ['/', '⬆️ Home'],
    ['/programming/', '⬅️ Programming'],
    {
      title: 'Setup',
      icon: 'fas fa-digging',
      collapsable: true,
      children: [
        '/setup/',
        '/setup/bag',
        '/setup/android',
        '/setup/ios',
        '/setup/macos',
        '/setup/windows',
      ],
    },
    ['/text-editors/', '➡️ Text Editors'],
  ],
  '/text-editors/': [
    ['/', '⬆️ Home'],
    ['/setup/', '⬅️ Setup'],
    {
      title: 'Text Editors',
      icon: 'fas file-alt',
      collapsable: true,
      children: [
        '/text-editors/',
        '/text-editors/vscode',
      ],
    },
    ['/GLOSSARY', '➡️ Glossary'],
  ],
  '/': [
    ['/', 'Home'],
    '/android/',
    '/comp-sci/',
    '/dat/',
    '/databases/',
    '/devops/',
    '/graphic-design/',
    '/ios/',
    '/linux/',
    '/lists/',
    '/pentesting/',
    '/productivity/',
    '/programming/',
    '/raspberry-pi/',
    '/selfhosted/',
    '/setup/',
    '/startup/',
    '/text-editors/',
    '/unix/',
    {
      collapsable: false,
      children: [
        '/GLOSSARY',
        '/LICENSE',
        '/meta',
        '/status',
      ],
    },
  ],
};
