name: CI

on: push

jobs:
  test:
    name: "Test Build"
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set Ruby v2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'

      - name: bundle install
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: bundle exec jekyll build
        run: bundle exec jekyll build
