name: CI

on: push

runs-on: ubuntu-latest

jobs:
  lint:
    name: "Lint check"
    steps:
    - name: Run ESLint
      uses: stefanoeb/eslint-action@1.0.0
    - name: Run Markdown Link Check
      uses: gaurav-nelson/github-action-markdown-link-check@0.2.0
